name: Close Pull Requests

on:
  pull_request_target:
    types: [opened]

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "We do not accept pull requests."
